'use client'
import { LogOut, Bell } from 'lucide-react'
const R='#B91C1C',DK='#0F172A',GR='#6B7280',GL='#9CA3AF',GB='#E2E8F0',W='#FFFFFF',GN='#059669',BL='#2563EB',OR='#D97706'
export{R,DK,GR,GL,GB,W,GN,BL,OR}

export function Logo({sz}){return<svg width={sz||24} height={sz||24} viewBox="0 0 100 100" fill="none"><circle cx="50" cy="50" r="38" stroke={R} strokeWidth="7" strokeLinecap="round" strokeDasharray="200" strokeDashoffset="40"/><circle cx="50" cy="50" r="24" stroke={R} strokeWidth="6" strokeLinecap="round" strokeDasharray="130" strokeDashoffset="30"/></svg>}
export function Badge({children,color,bg,sm}){return<span style={{display:'inline-flex',padding:sm?'2px 8px':'3px 10px',borderRadius:20,fontSize:sm?10:11,fontWeight:600,background:bg||(color||R)+'14',color:color||R}}>{children}</span>}
export function StatusBadge({status}){const c={Available:GN,Pending:OR,LEAD:BL,DESKING:OR,SUBMITTED:'#7C3AED',APPROVED:GN,FUNDED:GN,CONDITIONAL:OR,DECLINED:R,SIGNED:GN};return<Badge color={c[status]||GR}>{status}</Badge>}
export function Card({children,style:s,onClick}){return<div onClick={onClick} style={{background:W,borderRadius:12,padding:22,border:'1px solid '+GB,cursor:onClick?'pointer':'default',...s}}>{children}</div>}
export function Btn({children,primary,sm,danger,color,onClick,style:s,icon:I,disabled}){return<button disabled={disabled} onClick={onClick} style={{display:'inline-flex',alignItems:'center',gap:6,padding:sm?'6px 14px':'10px 20px',borderRadius:8,border:(primary||danger)?'none':'1px solid '+GB,background:disabled?'#D1D5DB':danger?R:primary?(color||R):W,color:(primary||danger)?W:DK,fontSize:sm?11:13,fontWeight:600,cursor:disabled?'not-allowed':'pointer',opacity:disabled?.6:1,...s}}>{I&&<I size={sm?13:15}/>}{children}</button>}
export function Input({label,value,onChange,ph,type,style:s,opts,req}){return<div style={{display:'flex',flexDirection:'column',gap:4,...s}}>{label&&<label style={{fontSize:11,fontWeight:600,color:GR}}>{label}{req&&<span style={{color:R}}> *</span>}</label>}{opts?<select value={value||''} onChange={e=>onChange&&onChange(e.target.value)} style={{padding:'8px 12px',borderRadius:8,border:'1px solid '+GB,fontSize:13,color:DK,background:W}}>{opts.map(o=><option key={o.v!=null?o.v:o} value={o.v!=null?o.v:o}>{o.l||o}</option>)}</select>:<input type={type||'text'} value={value||''} onChange={e=>onChange&&onChange(e.target.value)} placeholder={ph} style={{padding:'8px 12px',borderRadius:8,border:'1px solid '+GB,fontSize:13,color:DK}}/>}</div>}
export function DataTable({cols,data,onRow}){return<div style={{overflowX:'auto',borderRadius:10,border:'1px solid '+GB}}><table style={{width:'100%',borderCollapse:'collapse',fontSize:12.5}}><thead><tr style={{background:'#F9FAFB'}}>{cols.map(c=><th key={c.k} style={{textAlign:'left',padding:'11px 13px',fontWeight:600,color:GR,fontSize:10,textTransform:'uppercase',letterSpacing:.8,borderBottom:'1px solid '+GB}}>{c.l}</th>)}</tr></thead><tbody>{(!data||data.length===0)?<tr><td colSpan={cols.length} style={{padding:28,textAlign:'center',color:GR}}>No data yet</td></tr>:data.map((row,i)=><tr key={row.id||i} onClick={()=>onRow&&onRow(row)} style={{cursor:onRow?'pointer':'default',borderBottom:'1px solid #F3F4F6'}}>{cols.map(c=><td key={c.k} style={{padding:'11px 13px',color:DK}}>{c.r?c.r(row[c.k],row):row[c.k]}</td>)}</tr>)}</tbody></table></div>}
export function Shell({label,nav,active,setA,onOut,user,children}){return<div style={{display:'flex',minHeight:'100vh',background:'#FAFAFA'}}><div style={{width:220,background:W,borderRight:'1px solid '+GB,display:'flex',flexDirection:'column',position:'fixed',top:0,bottom:0,zIndex:10}}><div style={{padding:'16px',borderBottom:'1px solid '+GB,display:'flex',alignItems:'center',gap:10}}><Logo sz={24}/><div><div style={{fontSize:11,fontWeight:800,color:DK,letterSpacing:2,textTransform:'uppercase'}}>Car <span style={{color:R}}>Capitol</span></div><div style={{fontSize:9,color:GR}}>{label}</div></div></div><div style={{flex:1,padding:'8px',overflowY:'auto'}}>{nav.map(n=>{if(n.sep)return<div key={n.k} style={{fontSize:9,fontWeight:700,color:GL,padding:'14px 10px 4px',letterSpacing:1.5,textTransform:'uppercase'}}>{n.l}</div>;const isA=active===n.k,NI=n.i;return<button key={n.k} onClick={()=>setA(n.k)} style={{display:'flex',alignItems:'center',gap:9,width:'100%',padding:'8px 10px',borderRadius:8,border:'none',background:isA?'#FEF2F2':'transparent',color:isA?R:GR,fontWeight:isA?600:400,fontSize:12.5,cursor:'pointer',textAlign:'left',marginBottom:1}}><NI size={15}/><span style={{flex:1}}>{n.l}</span>{n.b&&<span style={{background:R,color:W,fontSize:9,fontWeight:700,borderRadius:10,padding:'1px 6px'}}>{n.b}</span>}</button>})}</div><div style={{padding:'10px',borderTop:'1px solid '+GB}}><div style={{fontSize:11,color:DK,fontWeight:600,padding:'4px 10px'}}>{user.full_name||user.email}</div><button onClick={onOut} style={{display:'flex',alignItems:'center',gap:7,width:'100%',padding:'8px 10px',borderRadius:8,border:'none',background:'transparent',color:GR,fontSize:12,cursor:'pointer'}}><LogOut size={14}/>Sign Out</button></div></div><div style={{flex:1,marginLeft:220}}><div style={{background:W,borderBottom:'1px solid '+GB,padding:'12px 24px',display:'flex',justifyContent:'space-between',alignItems:'center',position:'sticky',top:0,zIndex:5}}><h2 style={{fontSize:16,fontWeight:700,color:DK,margin:0}}>{(nav.find(n=>n.k===active)||{}).l||''}</h2><Bell size={18} color={GR}/></div><div style={{padding:24}}>{children}</div></div></div>}
export const GAP_PRICE=995
export const WTIERS=[{id:'W1',name:'PowerShield Basic',term:'36mo/36K',price:1495},{id:'W2',name:'PowerShield Plus',term:'48mo/48K',price:1995},{id:'W3',name:'PowerShield Premium',term:'60mo/60K',price:2995},{id:'W4',name:'PowerShield Platinum',term:'72mo/100K',price:3495}]
export function calcPay(pr,dn,apr,tm,gapOn,wp,ins){const tx=pr*0.0875,fe=895,fin=pr+tx+fe+(gapOn?GAP_PRICE:0)+wp-dn;const mr=apr/100/12;const mp=apr===0?fin/tm:fin*(mr*Math.pow(1+mr,tm))/(Math.pow(1+mr,tm)-1);return{mp:Math.round(mp),fin:Math.round(fin),tot:Math.round(mp+(ins||0))}}
